# Hardware configuration file

esphome:
  min_version: 2025.10.0

esp32:
  board: esp32-p4-evboard
  framework:
    type: esp-idf
    version: recommended
    advanced:
      enable_idf_experimental_features: true
  flash_size: 32MB
  cpu_frequency: 360MHz

psram:
  speed: 200MHz

preferences:
  flash_write_interval: 5min

esp_ldo:
  - channel: 3
    voltage: 2.5V

logger:
  level: debug
  logs:
    lvgl: info
  hardware_uart: UART0

#-------------------------------------------
# Network hardware
#-------------------------------------------  

# Ethernet settings
  
# ethernet:
  # type: IP101
  # mdc_pin: GPIO31
  # mdio_pin: GPIO52
  # clk: 
    # pin: GPIO50
    # mode: CLK_EXT_IN
  # phy_addr: 1
  # power_pin: GPIO51

# Wi-Fi settings

esp32_hosted:
  active_high: true
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17  

#-------------------------------------------
# LCD Back light
#-------------------------------------------

output:
  - platform: ledc
    id: gpio_backlight_pwm
    pin: GPIO26
    frequency: 100Hz
    inverted: true
    min_power: 0.1 # To prevent the backlight from being too dim
    max_power: 0.8 # To prevent overheating due to excessive lighting

  - id: internal_relay_1
    platform: gpio
    pin: GPIO32
    
  - id: internal_relay_2
    platform: gpio
    pin: GPIO46    
    
light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: display_backlight
    restore_mode: ALWAYS_ON

#-------------------------------------------
# Touchscreen gt911
#-------------------------------------------
i2c:
  - id: bus_a
    sda: GPIO7
    scl: GPIO8
    scan: true
    frequency: 400kHz

touchscreen:
  platform: gt911
  id: my_touchscreen
  display: my_display
  i2c_id: bus_a
  # on_touch:
    # - lambda: |-
        # ESP_LOGI("Touch", "Touch detected at x=%d, y=%d", touch.x, touch.y);
  # on_update:
    # - lambda: |-
          # for (auto touch: touches)  {
              # if (touch.state <= 2) {
                # ESP_LOGI("Touch points:", "id=%d x=%d, y=%d x.raw=%d, y.raw=%d", touch.id, touch.x, touch.y, touch.x_raw, touch.y_raw);
              # }
          # }


#-------------------------------------------
# Display
#-------------------------------------------
display:
  - platform: mipi_dsi
    id: my_display
    model: WAVESHARE-P4-86-PANEL
  
# Special LVGL settings required for this display  
lvgl:
  buffer_size: 100%
  byte_order: little_endian    

